Add Version + Release action
custom-components/readme pull request #11
Opened 2021-05-06 09:47 UTC by edenhaus

2021-05-26 21:57 UTC, edenhaus commented
@ludeeus Can you please review this PR or delegate it to the correct person?

2021-05-27 17:15 UTC, brianhanifin commented
This looks to make this compatible with Home Assistant 2021.06? Am I right?

2021-05-27 17:30 UTC, edenhaus commented
> This looks to make this compatible with Home Assistant 2021.06? Am I right?

Yes exactly

2021-05-31 08:59 UTC, ludeeus requested changes

2021-05-31 08:59 UTC, ludeeus commented on hacs.json
> +  "iot_class": "Local Push",
```suggestion
  "iot_class": "calculated",
```

2021-05-31 08:59 UTC, ludeeus commented on custom_components/readme/manifest.json
> +  "iot_class": "local_push"
```suggestion
  "iot_class": "calculated"
```

2021-05-31 08:59 UTC, ludeeus commented on custom_components/readme/const.py
> +INTEGRATION_VERSION = "0.2.1"
```suggestion
INTEGRATION_VERSION = "0.0.0"
```

2021-05-31 08:59 UTC, ludeeus commented on .github/workflows/hassfest.yaml
> +  pull_request:
```suggestion
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

2021-05-31 09:01 UTC, ludeeus commented
> Someone with enough rights please add `secrets.GITHUB_TOKEN`

This is not something you can add, that is a default special secret that GitHub injects to the action during runtime :+1:

2021-05-31 09:30 UTC, edenhaus commented
> > Someone with enough rights please add `secrets.GITHUB_TOKEN`
> 
> This is not something you can add, that is a default special secret that GitHub injects to the action during runtime +1

Thanks for clarification :)
I have committed your suggestions

2021-05-31 09:50 UTC, ludeeus commented on custom_components/readme/manifest.json
> +  "version": "v0.0.0",
```suggestion
  "version": "0.0.0",
```

2021-05-31 09:51 UTC, ludeeus approved these changes
Looks good :+1: :tada:

2021-05-31 09:52 UTC, merged

2021-05-31 18:07 UTC, brianhanifin reviewed
The release looks to have resolved the **no 'version' key** warning in the Home Assistant 2021.05.x log. This is resolved!

2021-05-31 18:16 UTC, ludeeus commented on custom_components/readme/const.py
> +INTEGRATION_VERSION = "0.0.0"
It's replaced here and in the manifest